name: Move new issues into Triage

on:
  issues:
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Add new issues
    steps:
    - name: Move NEW issues into the Velero Support Triage board
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/carlisia/projects/2'
        column_name: 'Needs Triage'
